### ISSUE TITLE
Add browser fallback

### ISSUE THREAD

**Issue by jamen** [jamen/pull-fetch#1]

**Comment by jamen** [comment]
Probably using [`pull-xhr`](https://github.com/ahdinosaur/pull-xhr)

**Comment by regular** [comment]
How about hyperquest?

**Comment by jamen** [comment]
I've never seen `hyperquest` before.  Looks like it would work.

However, I do like the barebones approach I've seen in some pull-stream packages.  Maybe in the future `stream-to-pull-stream` could be dropped completely.
