### ISSUE TITLE
fetch.json streams are marked as done pematurely

### ISSUE THREAD

**Issue by amsross** [jamen/pull-fetch#4]
It appears that the stream is marked as `done` during `pull.collect` in `fetch.result`, so subsequent functions that wait until a stream is marked as `done` don't seem to fire.

I may be mischaracterizing the issue as I've only just stumbled across pull-streams in general.

Here is an example for reproduction:
```
const nock = require("nock");
const fetch = require("pull-fetch");
const pull = require("pull-stream");

nock("http://example.com")
  .get("/")
  .reply(200, `{"msg": "success"}`)

pull(
  fetch.json("http://example.com"),
  pull.collect(console.log)) // never logs
```

**Comment by jamen** [comment]
Yeah, this does sound like an issue.  I made this module before I really understood how to make proper source streams, so I'm pretty sure I know what is wrong here.

I might be busy today (got a flight) and maybe tomorrow, but I will try to patch this when I can. I've been wanting to upgrade this package anyways.  If you need something sooner, I'm open to PRs and I can review.

Thanks!

**Comment by amsross** [comment]
I'm poking around to see if I can put up a PR, but I've got about 3 hours of pull-stream experience right now, so I'm not holding my breath.

If I can hack it, I'll try to put in a test or something too.

**Comment by amsross** [comment]
I spent some time on this yesterday but didn't have much luck. I created some tests to work against and submitted them in PR #5.

A sticking point for me is that this works:
```
      pull(
        pull.values(['{"foo":"bar"}']),
        fetch('https://example.com/', { method: 'POST', body: 'application/json' }),
        pull.asyncMap((resp, done) => pull(resp, pull.collect(done))),
        pull.map(Buffer.concat),
        pull.drain(null, t.end));
```

but this doesn't:
```
      pull(
        fetch.result('https://example.com'),
        pull.drain(done))
```

The only difference between the two being that `fetch()` is a through, and `fetch.result()` is a source. As far as I can tell, there's nothing wrong with the way `fetch.result()` is constructed or returned.

**Comment by regular** [comment]
I think I can help out here, see PR.
