### ISSUE TITLE
There's no way to get response headers

### ISSUE THREAD

**Issue by regular** [jamen/pull-fetch#7]
In our case, we'd like to display a download progress bar. We should think about how properties of the original response object could be exposed.

**Comment by jamen** [comment]
Yeah this is a problem I ran into as well, which after I thought about it made me refrain from using pull-stream for HTTP requests.

On second thought, an interface like [`pull-http-server`](https://www.npmjs.com/package/pull-http-server) could be adopted, where the headers are accessable in a plain object, and the response is streamed:

```js
fetch(options, response => {
  console.log(response.headers)
  pull(
    response.source,
    // ...
  )
})
```

**Comment by jamen** [comment]
I redid the API like such:

```js
const response = await fetch({
  host: 'api.example.com',
  path: '/foobar',
  method: 'POST'
})(
  values([ 'hello', 'world' ])
)

console.log(response.headers)
```

See the docs for more details.
